project_id = "pqlycsuxmyuqacxbldey"

[functions.ai-chat]
verify_jwt = false

[functions.create-customer]
verify_jwt = false

[functions.update-customer]
verify_jwt = false

[functions.approve-payment-request]
verify_jwt = false

[functions.create-payment-request]
verify_jwt = false

[functions.record-customer-payment]
verify_jwt = false